---
version: '3'

services:
  vanqc:
    container_name: vanqc
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/vanqc:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - vanqc
